### ISSUE TITLE
Repo license?

### ISSUE THREAD

**Issue by sterlingcrispin** [labstreaminglayer/LSL4Unity#27]
Hey! Thanks for working on this and posting it to GitHub! Could you add a MIT license or something like that to the repo? I believe lsl itself is MIT licensed it would be cool if this was too

**Comment by SamuelBG13** [comment]
Hello, 

May I also kindly ask for a License? I find the package very useful.  

Samuel

**Comment by SamuelBG13** [comment]
Hello,

May I also kindly ask for a License? I find the package could be very useful to us.

Samuel

**Comment by tstenner** [comment]
@xfleckx  wrote almost all the code, so he should decide if MIT is ok for him.

**Comment by xfleckx** [comment]
Sure thing, go for it!

**Comment by tstenner** [comment]
Thanks for the quick reply. Added in da88ccae91e398ae14b00191b2b59bbec7fd2ac7.
