### ISSUE TITLE
Can't Receive Marker in OpenViBE Acquisition Server, but LabRecorder can.

### ISSUE THREAD

**Issue by AeronZhang** [labstreaminglayer/LSL4Unity#42]
Hi all,
Does anyone use OpenViBE, I Can't Receive Marker in OpenViBE Acquisition Server, but LabRecorder can.
Note that, OpenViBE Acquisition Server can receiver the Signal.

**Comment by cboulay** [comment]
Is this a marker stream you're creating with LSL4Unity? If not then please close this issue and open elsewhere (maybe in sccn/liblsl).
Are both the marker stream and signal stream coming from the same computer? Is OpenViBE on the same computer?

There are many more details needed before we can help... and unless there's something specific in how LSL4Unity is creating the marker stream (unlikely), then this is probably the wrong repository to ask this question.

**Comment by AeronZhang** [comment]
Thank you for your reply! marker stream is created by LSL4Unity and I only use one PC(Win 10 64bit)
Both 32bit and 64bit OpenViBE Acquisition Server can't find the marker steam.
There are some informations may be help.
 
The signal stream must be of type cf_float32 and the marker stream cf_int32. ... The markers will be passed on as OpenViBE stimulations without conversion. Note that since OpenViBE stimulations are 64 bit integers, not all stimulations can be represented by LabStreamingLayer’s 32 bit integer stream.
from: http://openvibe.inria.fr/how-to-use-labstreaminglayer-in-openvibe/

**Comment by cboulay** [comment]
There's no practical reason why a marker stream has to be int32 other than that's what OpenViBE expects. Most of my markers streams send strings. Indeed, so does the default in LSL4Unity: https://github.com/labstreaminglayer/LSL4Unity/blob/master/Scripts/LSLMarkerStream.cs#L22

If you want to send markers that OpenViBE will read, without modifying OpenViBE, then you'll have to write your own code to manage markers and not use LSL4Unity's LSLMarkerStream script.

**Comment by AeronZhang** [comment]
Okay Thx a lot
