### ISSUE TITLE
Error adding LSL4Unity to my project

### ISSUE THREAD

**Issue by gprapas** [labstreaminglayer/LSL4Unity#45]
Hello, im trying to add LSL to my unity project following the instructions from this thread https://github.com/labstreaminglayer/LSL4Unity/tree/cboulay/cust_package , but both option 1 and 2 are failling. When im trying to import git package from URL i get this error: 
`[Package Manager Window] Unable to add package [https://github.com/labstreaminglayer/LSL4Unity.git  ]:
  Error when executing git command. fatal: unable to access 'https://github.com/labstreaminglayer/LSL4Unity.git  /': The requested URL returned error: 400

UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()`

and when im trying to add manually from manifest.json i get this:
An error occurred while resolving packages:
  Project has invalid dependencies:
    com.LSL.LSL4Unity: Package name 'com.LSL.LSL4Unity' is invalid.

Any help?
Thanks!

**Comment by cboulay** [comment]
It's probably not going to work directly from the URL until it's merged into the main branch. Those instructions are for the future, when it's merged.

Until then, clone the repo then add it from the folder you downloaded it to.

**Comment by gprapas** [comment]
I tried cloning the repo and adding it to unity but i get this error:
Assets\LSL4Unity\LSL.cs(487,173): error CS0117: 'liblsl.processing_options_t' does not contain a definition for 'proc_none' 
from the following line:
`public StreamInlet(StreamInfo info, int max_buflen = 360, int max_chunklen = 0, bool recover = true, processing_options_t postproc_flags = processing_options_t.proc_none)`

Any ideas on this?

**Comment by cboulay** [comment]
Closign as cust_package has been merged (and deleted!)
