### ISSUE TITLE
Error: The byte order conversion requested by the other party is not supported

### ISSUE THREAD

**Issue by gautamvishwanath** [labstreaminglayer/LSL4Unity#46]
Hi,

Whenever I try to send Unity marker streams to the Lab recorder, it gives me the error message (also attached):
The byte order conversion requested by the other party is not supported

Any ideas? Much appreciated, thanks!

![Error2](https://user-images.githubusercontent.com/103488159/194776104-0011cf0a-f4a7-4afe-847a-b7866a74e5ce.jpg)
![Error1](https://user-images.githubusercontent.com/103488159/194776108-5e09f93e-e22d-455d-8808-7b0b45ff7587.jpg)

**Comment by cboulay** [comment]
Can you share the code you're using to initialize your marker stream?
If possible, try to avoid int64 types.

**Comment by gautamvishwanath** [comment]
Thanks, I'm following a very simple tutorial here:
http://jmladeno.net/index.php/2017/12/01/tutorial-for-streaming-markers/

And attached as an image here is the code
<img width="1260" alt="Screenshot 2022-10-10 at 10 58 00" src="https://user-images.githubusercontent.com/103488159/194821281-4e5cb1ce-ff80-48fe-982e-ed6c1b930b32.png">

**Comment by gautamvishwanath** [comment]
Hi, sorry for the late reply. I wasn't well or around.
Thank you so much, got it working by testing one of the samples! :)
