### ISSUE TITLE
Cannot install LSL4Unity in 2021.3.26f1

### ISSUE THREAD

**Issue by KZcheese** [labstreaminglayer/LSL4Unity#49]
I am trying to install LSL4Unity in my Unity 2021.3.26f1 project and am receiving package not found errors. I followed the instructions for "Adding your project" from the readme.

Option 1 results in a Git error:
![image](https://github.com/labstreaminglayer/LSL4Unity/assets/8646140/f9573722-a29e-4521-b5ff-0d3b59e5e600)

Option 2 results in a package not found error:
![image](https://github.com/labstreaminglayer/LSL4Unity/assets/8646140/35c23025-fe19-4e49-882f-d2bef5049503)

**Comment by cboulay** [comment]
I just tried and it worked for me. I couldn't install 2021.3.26f1 so I used 2021.3.27f1, the nearest LTS version.

Try with a new project on 2021.3.27f1. If that doesn't work then I assume something's wrong with your system (firewall?).

**Comment by abinjakob** [comment]
I am facing similar issue with UNITY 2022.3.36f1
